### ISSUE TITLE
Source repository for sigpatches module missing from the guide

### ISSUE THREAD

**Issue by marco-calautti** [hacks-guide/Guide-WiiU#133]
I do not know exactly why only this module, which has crucial system modifying patches, is provided without its source.

I recreated the same exact module on my github, and built an rpx that behaves exactly as the one the guide provides.

If you are interested, you might consider linking the rpx to the releases of my github repo: https://github.com/marco-calautti/SigpatchesModuleWiiU

This would also give a bit more peace of mind to people like me that find a bit shady having to download some random binary without knowing where it is coming from (btw, I am not claiming the current rpx you share does anything malicious. I reversed its code and indeed does what it claims to do).

**Comment by GaryOderNichts** [comment]
I agree, all modules on the guide should have source code available.
Since Tiramisu doesn't come with any sigpatches, this was something quickly put together to not break existing setups with injects and custom channels.
Thanks for (re-)creating the module, I'm going to update the link in the guide.
